// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phftjfcjnpmooyqgwfzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZnRqZmNqbnBtb295cWd3Znp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDM5NDcsImV4cCI6MjA2MjQxOTk0N30.ynjL7n72SGO-5Bi61BixWI98S1wTf2a8RFDaDBL4oQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);